"""adds dislikes and loves relationships to user and track entities

Revision ID: 32a32abfb1f8
Revises: 504e6c076cee
Create Date: 2026-01-13 12:30:18.103945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a32abfb1f8'
down_revision: Union[str, Sequence[str], None] = '504e6c076cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks_dislikes',
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', 'user_id')
    )
    op.create_index(op.f('ix_tracks_dislikes_track_id'), 'tracks_dislikes', ['track_id'], unique=False)
    op.create_index(op.f('ix_tracks_dislikes_user_id'), 'tracks_dislikes', ['user_id'], unique=False)
    op.create_table('tracks_loves',
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', 'user_id')
    )
    op.create_index(op.f('ix_tracks_loves_track_id'), 'tracks_loves', ['track_id'], unique=False)
    op.create_index(op.f('ix_tracks_loves_user_id'), 'tracks_loves', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracks_loves_user_id'), table_name='tracks_loves')
    op.drop_index(op.f('ix_tracks_loves_track_id'), table_name='tracks_loves')
    op.drop_table('tracks_loves')
    op.drop_index(op.f('ix_tracks_dislikes_user_id'), table_name='tracks_dislikes')
    op.drop_index(op.f('ix_tracks_dislikes_track_id'), table_name='tracks_dislikes')
    op.drop_table('tracks_dislikes')
    # ### end Alembic commands ###
