"""adds file_id field to 'Track' entity to separate unique id from file_id in backblazeb2

Revision ID: 3956e0172c00
Revises: 7ffe47c481ec
Create Date: 2025-12-23 10:04:37.725665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3956e0172c00'
down_revision: Union[str, Sequence[str], None] = '7ffe47c481ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('file_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_tracks_file_id'), 'tracks', ['file_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracks_file_id'), table_name='tracks')
    op.drop_column('tracks', 'file_id')
    # ### end Alembic commands ###
