"""adds like relationship bettwen user and track entities

Revision ID: 504e6c076cee
Revises: c9a9ea1b8977
Create Date: 2026-01-13 12:23:35.989621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504e6c076cee'
down_revision: Union[str, Sequence[str], None] = 'c9a9ea1b8977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks_likes',
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', 'user_id')
    )
    op.create_index(op.f('ix_tracks_likes_track_id'), 'tracks_likes', ['track_id'], unique=False)
    op.create_index(op.f('ix_tracks_likes_user_id'), 'tracks_likes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracks_likes_user_id'), table_name='tracks_likes')
    op.drop_index(op.f('ix_tracks_likes_track_id'), table_name='tracks_likes')
    op.drop_table('tracks_likes')
    # ### end Alembic commands ###
