"""adds tables to keep track on playlists stats

Revision ID: 7f487ec346c7
Revises: 32a32abfb1f8
Create Date: 2026-01-29 22:59:47.244010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f487ec346c7'
down_revision: Union[str, Sequence[str], None] = '32a32abfb1f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists_dislikes',
    sa.Column('playlist_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id', 'user_id')
    )
    op.create_index(op.f('ix_playlists_dislikes_playlist_id'), 'playlists_dislikes', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playlists_dislikes_user_id'), 'playlists_dislikes', ['user_id'], unique=False)
    op.create_table('playlists_likes',
    sa.Column('playlist_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id', 'user_id')
    )
    op.create_index(op.f('ix_playlists_likes_playlist_id'), 'playlists_likes', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playlists_likes_user_id'), 'playlists_likes', ['user_id'], unique=False)
    op.create_table('playlists_loves',
    sa.Column('playlist_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id', 'user_id')
    )
    op.create_index(op.f('ix_playlists_loves_playlist_id'), 'playlists_loves', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playlists_loves_user_id'), 'playlists_loves', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlists_loves_user_id'), table_name='playlists_loves')
    op.drop_index(op.f('ix_playlists_loves_playlist_id'), table_name='playlists_loves')
    op.drop_table('playlists_loves')
    op.drop_index(op.f('ix_playlists_likes_user_id'), table_name='playlists_likes')
    op.drop_index(op.f('ix_playlists_likes_playlist_id'), table_name='playlists_likes')
    op.drop_table('playlists_likes')
    op.drop_index(op.f('ix_playlists_dislikes_user_id'), table_name='playlists_dislikes')
    op.drop_index(op.f('ix_playlists_dislikes_playlist_id'), table_name='playlists_dislikes')
    op.drop_table('playlists_dislikes')
    # ### end Alembic commands ###
