"""adds indexing to foreign keys in relationships

Revision ID: 7ffe47c481ec
Revises: 89f7bc1a63a2
Create Date: 2025-12-23 09:26:19.718943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ffe47c481ec'
down_revision: Union[str, Sequence[str], None] = '89f7bc1a63a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_playlists_author_id'), 'playlists', ['author_id'], unique=False)
    op.create_index(op.f('ix_playlists_tracks_playlist_id'), 'playlists_tracks', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playlists_tracks_track_id'), 'playlists_tracks', ['track_id'], unique=False)
    op.create_index(op.f('ix_tracks_uploaded_by'), 'tracks', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracks_uploaded_by'), table_name='tracks')
    op.drop_index(op.f('ix_playlists_tracks_track_id'), table_name='playlists_tracks')
    op.drop_index(op.f('ix_playlists_tracks_playlist_id'), table_name='playlists_tracks')
    op.drop_index(op.f('ix_playlists_author_id'), table_name='playlists')
    # ### end Alembic commands ###
