"""adds stats and uploader field to 'Track' entity

Revision ID: 89f7bc1a63a2
Revises: c02033598c3f
Create Date: 2025-12-23 05:05:32.534018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f7bc1a63a2'
down_revision: Union[str, Sequence[str], None] = 'c02033598c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('likes', sa.BigInteger(), nullable=False))
    op.add_column('tracks', sa.Column('dislikes', sa.BigInteger(), nullable=False))
    op.add_column('tracks', sa.Column('plays', sa.BigInteger(), nullable=False))
    op.add_column('tracks', sa.Column('loves', sa.BigInteger(), nullable=False))
    op.add_column('tracks', sa.Column('uploaded_by', sa.String(), nullable=False))
    op.alter_column('tracks', 'size',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_foreign_key(None, 'tracks', 'users', ['uploaded_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.alter_column('tracks', 'size',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('tracks', 'uploaded_by')
    op.drop_column('tracks', 'loves')
    op.drop_column('tracks', 'plays')
    op.drop_column('tracks', 'dislikes')
    op.drop_column('tracks', 'likes')
    # ### end Alembic commands ###
