"""fix relationship bettwen 'Playlist' and 'Track'

Revision ID: c02033598c3f
Revises: 6f1857b8a1c2
Create Date: 2025-12-21 17:59:02.344833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c02033598c3f'
down_revision: Union[str, Sequence[str], None] = '6f1857b8a1c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
