"""adds indexing to 'name' and 'author_name' properties of entity 'Track'

Revision ID: c92694dc99ed
Revises: 7f487ec346c7
Create Date: 2026-02-06 19:27:14.647346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c92694dc99ed'
down_revision: Union[str, Sequence[str], None] = '7f487ec346c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tracks_author_name'), 'tracks', ['author_name'], unique=False)
    op.create_index(op.f('ix_tracks_name'), 'tracks', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracks_name'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_author_name'), table_name='tracks')
    # ### end Alembic commands ###
