"""adds content_hash field to 'Track' entity for deduplication feature

Revision ID: c9a9ea1b8977
Revises: 3956e0172c00
Create Date: 2025-12-23 10:48:42.492480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9a9ea1b8977'
down_revision: Union[str, Sequence[str], None] = '3956e0172c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('content_hash', sa.String(), nullable=False))
    op.create_index(op.f('ix_tracks_content_hash'), 'tracks', ['content_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracks_content_hash'), table_name='tracks')
    op.drop_column('tracks', 'content_hash')
    # ### end Alembic commands ###
