"""adds 'PlayList' entity and relationship with 'User' entity

Revision ID: ced98093544c
Revises: 9dff5f25073e
Create Date: 2025-12-19 21:10:53.563525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ced98093544c'
down_revision: Union[str, Sequence[str], None] = '9dff5f25073e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
